Dill locking & boosting UI
pickle-finance/pickle-ui pull request #6
Opened 2021-02-03 13:16 UTC by 0xkoffee

2021-02-05 08:45 UTC, mannyreimi88 requested changes
@0xkoffee great job. Let's consider down-the-line to chunk the work and do the reviews on an ad-hoc basis if that's OK with you. From the reviewer's POV, it's hardcore to go through 22 files and 1,500+ lines of code in a single sitting.

A few matters:
- [x] no preview of how much `DILL` I am getting.
- [x] difficult to change dates without some buttons or presets. Consider adding "1 week", "1 month", "6 months", "1 year", "2 years", "3 years", and "4 years".
- [x] all "lock for" dates are expressed in weeks. For larger numbers, users may be more familiar with "months" or even "years" as units of measurement i.e. "4 years" rather than "208 weeks"
- [x] default lock for is 1 "weeks" instead of "week".
- [x] if there is a decay in the voting power of `DILL` this is not reflected in the UI.

The last matter I am not sure about, but if the user will need to authorize the app for spending `PICKLEs` there is no indication of this in the UI.

2021-03-08 14:15 UTC, mannyreimi88 commented
@larrythecucumber321 some preliminary observations on the `/gauges` route based on our discussions and this screenshot:

![](https://camo.githubusercontent.com/364f6a4c2872e8d79014335b96cdd22c78ea0dc711d3383e29c7c1ae01d0fd21/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3830323335313630373330333131303635362f3831363130313638393636383031303031342f756e6b6e6f776e2e706e67)

- [ ] give **Boost** its own element in a card-like format, like the **Active** box, similar to what we did with the **Zap** element on the home page.
- [ ] some instruction would be welcome, for example, **Input a weight for the boost you'd like to give each gauge. The app will automatically determine the final distribution of your boosts and confirm before applying them**.
- [ ] consider a two-step process:
    - [ ] first, the user inputs his desired weights on each gauge
    - [ ] on clicking **Boost**, a modal window appears, with the distribution (i.e. if the user added 1, 1, 1, to gauges a, b, and c he'll get a modal window saying gauge a 33.33%, gauge b 33.33%, gauge c 33.33%). Clicking **Apply Boosts** will set the transaction.
- [ ] the **Boost** card should only appear active for users who have locked DILL, otherwise, it should direct users to lock in DILL (if they have PICKLE, otherwise prompt them to acquire PICKLE).
- [ ] the current "Boost" (i.e. 1.000x) should appear in the card, and "Boost" to receive (i.e. 2.500x) should appear in the confirmation modal.

2021-04-11 21:54 UTC, Cipioo commented on features/DILL/Claim.tsx
> +  const dillAPY =
This appears to be calculating the amount of return per week. multiply by 52 to get apy.

2021-04-11 22:26 UTC, Cipioo commented on features/DILL/Claim.tsx
> +      ? dillStats.weeklyDistribution / dillStats.lockedValue
This appears to be calculating the amount of return per week. multiply by 52 to get apy. #
```suggestion
      ? dillStats.weeklyDistribution / dillStats.lockedValue * 52
```

2021-04-11 22:37 UTC, Cipioo commented on features/DILL/Claim.tsx
> +      ? dillStats.weeklyDistribution / dillStats.lockedValue
If you want it more accurate you can multiply by 52.17857

2021-04-20 03:09 UTC, larrythecucumber321 approved these changes

2021-04-20 03:18 UTC, merged